### ISSUE TITLE
Drop not working on mobile

### ISSUE THREAD

**Issue by pimboden** [emiliorizzo/vue-dialog-drag#1]
Hello. 
This is a very nice components!
Any plans to make it work in mobile devices?
It creates dialog , and I can move the around. but I cant drop them.
Keep up the good work!

**Comment by emiliorizzo** [comment]
At the moment the drop not work on touch devices..... README -> Touch support (only for drag, not for drop). 
 Im rewriting the component now to clean some bugs. I plan update in next days.
Thanks for your comments!

**Comment by emiliorizzo** [comment]
Works on firefox.....
