### ISSUE TITLE
How to remove Dialog

### ISSUE THREAD

**Issue by chaule97** [emiliorizzo/vue-dialog-drag#11]
I want to click the close button then remove dialog. Please help me...

**Comment by emiliorizzo** [comment]
Did you see the [example](https://emiliorizzo.github.io/vue-dialog-drag/)?
The dialog should be closed by clicking on the button.

**Comment by thukuwanjiku** [comment]
@emiliorizzo The close button isn't working. It's not working on my code, neither is it working on the sample [fiddle](https://jsfiddle.net/emii/g7hojq7m/) you have in the docs. But somehow it is working in your [demo](https://emiliorizzo.github.io/vue-dialog-drag/). Please check.

[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-7cv3u?fontsize=14&hidenavigation=1&theme=dark)

**Comment by emiliorizzo** [comment]
HI @thukuwanjiku , I´m sorry the late answer, but I don't known why I didn't see this comment before.
I've fixed your example in: https://codesandbox.io/s/vue-template-4x70j
