### ISSUE TITLE
Is there a way to prevent dragging outside the browser window

### ISSUE THREAD

**Issue by mdr1384** [emiliorizzo/vue-dialog-drag#3]
For example on your Fiddle I can drag the dialogs right off the browser and drop them in my Outlook window (which causes an email with the dialog ID in the body) -- but now the dialog is GONE for good until I refresh the page.   We need some way to prevent the dialog being "lost", either limit travel to a bounding DIV/window, or else "fail" back to initial position when dropped outside a bounding DIV/window.   FYI there is an example of it using [jQuery drag plugin here](https://stackoverflow.com/questions/4032605/javascript-prevent-drag-and-drop-outside-browser-window).

**Comment by emiliorizzo** [comment]
see #2  
and updated fiddle: https://jsfiddle.net/4s15vfdx/5/
Reopen the issue if you need.
Thanks

**Comment by mdr1384** [comment]
Yes, thanks it works good -- sorry I didn't see that other issue.

**Comment by emiliorizzo** [comment]
:+1:
